name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.sllvn.example
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: List provisioning profiles
      run: |
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
        grep -l "com.sllvn.example" ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision || echo "No matching profiles found"
    - name: Check provisioning profile content
      run: |
        security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/b0c22e0f-37ac-4bf2-bfb3-6bded5144f4d.mobileprovision | grep -A3 -B3 "application-identifier"
    - name: "#️⃣ Generate Build Number"
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}
    - uses: yukiarrr/ios-build-action@v1.12.0
      with:
        project-path: Example-iOS/Example-iOS.xcodeproj
        p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
        p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
        certificate-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: .build/Artifacts/Example-iOS.ipa/Example-iOS.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
